language: php

php:
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer update --prefer-source --dev

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v
